apiVersion: apps/v1
kind: dev-webapp
metadata:
  name: dev-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-webapp
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: dev-webapp
          image: httpd:latest
          ports:
            - containerPort: 6379
          env:
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: dev-wedapp
metadata:
  name: dev-webapp
spec:
  selector:
    app: dev-webapp
  ports:
    - port: 83
      targetPort: 6379
  type: LoadBalancer
