apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: yeasy/simple-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
         
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 8081
      targetPort: 80
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081           # this is service port 80
      targetPort: 80  
