apiVersion: apps/v1
kind: webapp
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: httpd:latest
          ports:
            - containerPort: 6379
          env:
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: wedapp
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 83
      targetPort: 6379
  type: LoadBalancer
